[MeterBar1]
Meter=Bar
MeasureName=One

[MeterBar2]
Meter=Bar
MeasureName=One

[MeterBar3]
Meter=Bar
MeasureName=One

[MeterBar4]
Meter=Bar
MeasureName=One

[MeterBar5]
Meter=Bar
MeasureName=One

[MeterBar6]
Meter=Bar
MeasureName=One

[MeterBar7]
Meter=Bar
MeasureName=One

[MeterBar8]
Meter=Bar
MeasureName=One

[MeterBar9]
Meter=Bar
MeasureName=One

[MeterBar10]
Meter=Bar
MeasureName=One

[MeterBar11]
Meter=Bar
MeasureName=One

[MeterBar12]
Meter=Bar
MeasureName=One

[MeterBar13]
Meter=Bar
MeasureName=One

[MeterBar14]
Meter=Bar
MeasureName=One

[MeterBar15]
Meter=Bar
MeasureName=One

[MeterBar16]
Meter=Bar
MeasureName=One

[MeterBar17]
Meter=Bar
MeasureName=One

[MeterBar18]
Meter=Bar
MeasureName=One

[MeterBar19]
Meter=Bar
MeasureName=One

[MeterBar20]
Meter=Bar
MeasureName=One

[MeterBar21]
Meter=Bar
MeasureName=One

[MeterBar22]
Meter=Bar
MeasureName=One

[MeterBar23]
Meter=Bar
MeasureName=One

[MeterBar24]
Meter=Bar
MeasureName=One

[MeterBar25]
Meter=Bar
MeasureName=One

[MeterBar26]
Meter=Bar
MeasureName=One

[MeterBar27]
Meter=Bar
MeasureName=One

[MeterBar28]
Meter=Bar
MeasureName=One

[MeterBar29]
Meter=Bar
MeasureName=One

[MeterBar30]
Meter=Bar
MeasureName=One

[MeterBar31]
Meter=Bar
MeasureName=One

[MeterBar32]
Meter=Bar
MeasureName=One

[MeterBar33]
Meter=Bar
MeasureName=One

[MeterBar34]
Meter=Bar
MeasureName=One

[MeterBar35]
Meter=Bar
MeasureName=One

[MeterBar36]
Meter=Bar
MeasureName=One

[MeterBar37]
Meter=Bar
MeasureName=One

[MeterBar38]
Meter=Bar
MeasureName=One

[MeterBar39]
Meter=Bar
MeasureName=One

[MeterBar40]
Meter=Bar
MeasureName=One

[MeterBar41]
Meter=Bar
MeasureName=One

[MeterBar42]
Meter=Bar
MeasureName=One

[MeterBar43]
Meter=Bar
MeasureName=One

[MeterBar44]
Meter=Bar
MeasureName=One

[MeterBar45]
Meter=Bar
MeasureName=One

[MeterBar46]
Meter=Bar
MeasureName=One

[MeterBar47]
Meter=Bar
MeasureName=One

[MeterBar48]
Meter=Bar
MeasureName=One

[MeterBar49]
Meter=Bar
MeasureName=One

[MeterBar50]
Meter=Bar
MeasureName=One

[MeterBar51]
Meter=Bar
MeasureName=One

[MeterBar52]
Meter=Bar
MeasureName=One

[MeterBar53]
Meter=Bar
MeasureName=One

[MeterBar54]
Meter=Bar
MeasureName=One

[MeterBar55]
Meter=Bar
MeasureName=One

[MeterBar56]
Meter=Bar
MeasureName=One

[MeterBar57]
Meter=Bar
MeasureName=One

[MeterBar58]
Meter=Bar
MeasureName=One

[MeterBar59]
Meter=Bar
MeasureName=One

[MeterBar60]
Meter=Bar
MeasureName=One

[MeterBar61]
Meter=Bar
MeasureName=One

[MeterBar62]
Meter=Bar
MeasureName=One

[MeterBar63]
Meter=Bar
MeasureName=One

[MeterBar64]
Meter=Bar
MeasureName=One

[MeterBar65]
Meter=Bar
MeasureName=One

[MeterBar66]
Meter=Bar
MeasureName=One

[MeterBar67]
Meter=Bar
MeasureName=One

[MeterBar68]
Meter=Bar
MeasureName=One

[MeterBar69]
Meter=Bar
MeasureName=One

[MeterBar70]
Meter=Bar
MeasureName=One

[MeterBar71]
Meter=Bar
MeasureName=One

[MeterBar72]
Meter=Bar
MeasureName=One

[MeterBar73]
Meter=Bar
MeasureName=One

[MeterBar74]
Meter=Bar
MeasureName=One

[MeterBar75]
Meter=Bar
MeasureName=One

[MeterBar76]
Meter=Bar
MeasureName=One

[MeterBar77]
Meter=Bar
MeasureName=One

[MeterBar78]
Meter=Bar
MeasureName=One

[MeterBar79]
Meter=Bar
MeasureName=One

[MeterBar80]
Meter=Bar
MeasureName=One

[MeterBar81]
Meter=Bar
MeasureName=One

[MeterBar82]
Meter=Bar
MeasureName=One

[MeterBar83]
Meter=Bar
MeasureName=One

[MeterBar84]
Meter=Bar
MeasureName=One

[MeterBar85]
Meter=Bar
MeasureName=One

[MeterBar86]
Meter=Bar
MeasureName=One

[MeterBar87]
Meter=Bar
MeasureName=One

[MeterBar88]
Meter=Bar
MeasureName=One

[MeterBar89]
Meter=Bar
MeasureName=One

[MeterBar90]
Meter=Bar
MeasureName=One

[MeterBar91]
Meter=Bar
MeasureName=One

[MeterBar92]
Meter=Bar
MeasureName=One

[MeterBar93]
Meter=Bar
MeasureName=One

[MeterBar94]
Meter=Bar
MeasureName=One

[MeterBar95]
Meter=Bar
MeasureName=One

[MeterBar96]
Meter=Bar
MeasureName=One

[MeterBar97]
Meter=Bar
MeasureName=One

[MeterBar98]
Meter=Bar
MeasureName=One

[MeterBar99]
Meter=Bar
MeasureName=One

[MeterBar100]
Meter=Bar
MeasureName=One

[MeterBar101]
Meter=Bar
MeasureName=One

[MeterBar102]
Meter=Bar
MeasureName=One

[MeterBar103]
Meter=Bar
MeasureName=One

[MeterBar104]
Meter=Bar
MeasureName=One

[MeterBar105]
Meter=Bar
MeasureName=One

[MeterBar106]
Meter=Bar
MeasureName=One

[MeterBar107]
Meter=Bar
MeasureName=One

[MeterBar108]
Meter=Bar
MeasureName=One

[MeterBar109]
Meter=Bar
MeasureName=One

[MeterBar110]
Meter=Bar
MeasureName=One

[MeterBar111]
Meter=Bar
MeasureName=One

[MeterBar112]
Meter=Bar
MeasureName=One

[MeterBar113]
Meter=Bar
MeasureName=One

[MeterBar114]
Meter=Bar
MeasureName=One

[MeterBar115]
Meter=Bar
MeasureName=One

[MeterBar116]
Meter=Bar
MeasureName=One

[MeterBar117]
Meter=Bar
MeasureName=One

[MeterBar118]
Meter=Bar
MeasureName=One

[MeterBar119]
Meter=Bar
MeasureName=One

[MeterBar120]
Meter=Bar
MeasureName=One

[MeterBar121]
Meter=Bar
MeasureName=One

[MeterBar122]
Meter=Bar
MeasureName=One

[MeterBar123]
Meter=Bar
MeasureName=One

[MeterBar124]
Meter=Bar
MeasureName=One

[MeterBar125]
Meter=Bar
MeasureName=One

[MeterBar126]
Meter=Bar
MeasureName=One

[MeterBar127]
Meter=Bar
MeasureName=One

[MeterBar128]
Meter=Bar
MeasureName=One

[MeterBar129]
Meter=Bar
MeasureName=One

[MeterBar130]
Meter=Bar
MeasureName=One

[MeterBar131]
Meter=Bar
MeasureName=One

[MeterBar132]
Meter=Bar
MeasureName=One

[MeterBar133]
Meter=Bar
MeasureName=One

[MeterBar134]
Meter=Bar
MeasureName=One

[MeterBar135]
Meter=Bar
MeasureName=One

[MeterBar136]
Meter=Bar
MeasureName=One

[MeterBar137]
Meter=Bar
MeasureName=One

[MeterBar138]
Meter=Bar
MeasureName=One

[MeterBar139]
Meter=Bar
MeasureName=One

[MeterBar140]
Meter=Bar
MeasureName=One

[MeterBar141]
Meter=Bar
MeasureName=One

[MeterBar142]
Meter=Bar
MeasureName=One

[MeterBar143]
Meter=Bar
MeasureName=One

[MeterBar144]
Meter=Bar
MeasureName=One

[MeterBar145]
Meter=Bar
MeasureName=One

[MeterBar146]
Meter=Bar
MeasureName=One

[MeterBar147]
Meter=Bar
MeasureName=One

[MeterBar148]
Meter=Bar
MeasureName=One

[MeterBar149]
Meter=Bar
MeasureName=One

[MeterBar150]
Meter=Bar
MeasureName=One

[MeterBar151]
Meter=Bar
MeasureName=One

[MeterBar152]
Meter=Bar
MeasureName=One

[MeterBar153]
Meter=Bar
MeasureName=One

[MeterBar154]
Meter=Bar
MeasureName=One

[MeterBar155]
Meter=Bar
MeasureName=One

[MeterBar156]
Meter=Bar
MeasureName=One

[MeterBar157]
Meter=Bar
MeasureName=One

[MeterBar158]
Meter=Bar
MeasureName=One

[MeterBar159]
Meter=Bar
MeasureName=One

[MeterBar160]
Meter=Bar
MeasureName=One

[MeterBar161]
Meter=Bar
MeasureName=One

[MeterBar162]
Meter=Bar
MeasureName=One

[MeterBar163]
Meter=Bar
MeasureName=One

[MeterBar164]
Meter=Bar
MeasureName=One

[MeterBar165]
Meter=Bar
MeasureName=One

[MeterBar166]
Meter=Bar
MeasureName=One

[MeterBar167]
Meter=Bar
MeasureName=One

[MeterBar168]
Meter=Bar
MeasureName=One

[MeterBar169]
Meter=Bar
MeasureName=One

[MeterBar170]
Meter=Bar
MeasureName=One

[MeterBar171]
Meter=Bar
MeasureName=One

[MeterBar172]
Meter=Bar
MeasureName=One

[MeterBar173]
Meter=Bar
MeasureName=One

[MeterBar174]
Meter=Bar
MeasureName=One

[MeterBar175]
Meter=Bar
MeasureName=One

[MeterBar176]
Meter=Bar
MeasureName=One

[MeterBar177]
Meter=Bar
MeasureName=One

[MeterBar178]
Meter=Bar
MeasureName=One

[MeterBar179]
Meter=Bar
MeasureName=One

[MeterBar180]
Meter=Bar
MeasureName=One

[MeterBar181]
Meter=Bar
MeasureName=One

[MeterBar182]
Meter=Bar
MeasureName=One

[MeterBar183]
Meter=Bar
MeasureName=One

[MeterBar184]
Meter=Bar
MeasureName=One

[MeterBar185]
Meter=Bar
MeasureName=One

[MeterBar186]
Meter=Bar
MeasureName=One

[MeterBar187]
Meter=Bar
MeasureName=One

[MeterBar188]
Meter=Bar
MeasureName=One

[MeterBar189]
Meter=Bar
MeasureName=One

[MeterBar190]
Meter=Bar
MeasureName=One

[MeterBar191]
Meter=Bar
MeasureName=One

[MeterBar192]
Meter=Bar
MeasureName=One

[MeterBar193]
Meter=Bar
MeasureName=One

[MeterBar194]
Meter=Bar
MeasureName=One

[MeterBar195]
Meter=Bar
MeasureName=One

[MeterBar196]
Meter=Bar
MeasureName=One

[MeterBar197]
Meter=Bar
MeasureName=One

[MeterBar198]
Meter=Bar
MeasureName=One

[MeterBar199]
Meter=Bar
MeasureName=One

[MeterBar200]
Meter=Bar
MeasureName=One

[MeterBar201]
Meter=Bar
MeasureName=One

[MeterBar202]
Meter=Bar
MeasureName=One

[MeterBar203]
Meter=Bar
MeasureName=One

[MeterBar204]
Meter=Bar
MeasureName=One

[MeterBar205]
Meter=Bar
MeasureName=One

[MeterBar206]
Meter=Bar
MeasureName=One

[MeterBar207]
Meter=Bar
MeasureName=One

[MeterBar208]
Meter=Bar
MeasureName=One

[MeterBar209]
Meter=Bar
MeasureName=One

[MeterBar210]
Meter=Bar
MeasureName=One

[MeterBar211]
Meter=Bar
MeasureName=One

[MeterBar212]
Meter=Bar
MeasureName=One

[MeterBar213]
Meter=Bar
MeasureName=One

[MeterBar214]
Meter=Bar
MeasureName=One

[MeterBar215]
Meter=Bar
MeasureName=One

[MeterBar216]
Meter=Bar
MeasureName=One

[MeterBar217]
Meter=Bar
MeasureName=One

[MeterBar218]
Meter=Bar
MeasureName=One

[MeterBar219]
Meter=Bar
MeasureName=One

[MeterBar220]
Meter=Bar
MeasureName=One

[MeterBar221]
Meter=Bar
MeasureName=One

[MeterBar222]
Meter=Bar
MeasureName=One

[MeterBar223]
Meter=Bar
MeasureName=One

[MeterBar224]
Meter=Bar
MeasureName=One

[MeterBar225]
Meter=Bar
MeasureName=One

[MeterBar226]
Meter=Bar
MeasureName=One

[MeterBar227]
Meter=Bar
MeasureName=One

[MeterBar228]
Meter=Bar
MeasureName=One

[MeterBar229]
Meter=Bar
MeasureName=One

[MeterBar230]
Meter=Bar
MeasureName=One

[MeterBar231]
Meter=Bar
MeasureName=One

[MeterBar232]
Meter=Bar
MeasureName=One

[MeterBar233]
Meter=Bar
MeasureName=One

[MeterBar234]
Meter=Bar
MeasureName=One

[MeterBar235]
Meter=Bar
MeasureName=One

[MeterBar236]
Meter=Bar
MeasureName=One

[MeterBar237]
Meter=Bar
MeasureName=One

[MeterBar238]
Meter=Bar
MeasureName=One

[MeterBar239]
Meter=Bar
MeasureName=One

[MeterBar240]
Meter=Bar
MeasureName=One

[MeterBar241]
Meter=Bar
MeasureName=One

[MeterBar242]
Meter=Bar
MeasureName=One

[MeterBar243]
Meter=Bar
MeasureName=One

[MeterBar244]
Meter=Bar
MeasureName=One

[MeterBar245]
Meter=Bar
MeasureName=One

[MeterBar246]
Meter=Bar
MeasureName=One

[MeterBar247]
Meter=Bar
MeasureName=One

[MeterBar248]
Meter=Bar
MeasureName=One

[MeterBar249]
Meter=Bar
MeasureName=One

[MeterBar250]
Meter=Bar
MeasureName=One

[MeterBar251]
Meter=Bar
MeasureName=One

[MeterBar252]
Meter=Bar
MeasureName=One

[MeterBar253]
Meter=Bar
MeasureName=One

[MeterBar254]
Meter=Bar
MeasureName=One

[MeterBar255]
Meter=Bar
MeasureName=One

[MeterBar256]
Meter=Bar
MeasureName=One

[MeterBar257]
Meter=Bar
MeasureName=One

[MeterBar258]
Meter=Bar
MeasureName=One

[MeterBar259]
Meter=Bar
MeasureName=One

[MeterBar260]
Meter=Bar
MeasureName=One

[MeterBar261]
Meter=Bar
MeasureName=One

[MeterBar262]
Meter=Bar
MeasureName=One

[MeterBar263]
Meter=Bar
MeasureName=One

[MeterBar264]
Meter=Bar
MeasureName=One

[MeterBar265]
Meter=Bar
MeasureName=One

[MeterBar266]
Meter=Bar
MeasureName=One

[MeterBar267]
Meter=Bar
MeasureName=One

[MeterBar268]
Meter=Bar
MeasureName=One

[MeterBar269]
Meter=Bar
MeasureName=One

[MeterBar270]
Meter=Bar
MeasureName=One

[MeterBar271]
Meter=Bar
MeasureName=One

[MeterBar272]
Meter=Bar
MeasureName=One

[MeterBar273]
Meter=Bar
MeasureName=One

[MeterBar274]
Meter=Bar
MeasureName=One

[MeterBar275]
Meter=Bar
MeasureName=One

[MeterBar276]
Meter=Bar
MeasureName=One

[MeterBar277]
Meter=Bar
MeasureName=One

[MeterBar278]
Meter=Bar
MeasureName=One

[MeterBar279]
Meter=Bar
MeasureName=One

[MeterBar280]
Meter=Bar
MeasureName=One

[MeterBar281]
Meter=Bar
MeasureName=One

[MeterBar282]
Meter=Bar
MeasureName=One

[MeterBar283]
Meter=Bar
MeasureName=One

[MeterBar284]
Meter=Bar
MeasureName=One

[MeterBar285]
Meter=Bar
MeasureName=One

[MeterBar286]
Meter=Bar
MeasureName=One

[MeterBar287]
Meter=Bar
MeasureName=One

[MeterBar288]
Meter=Bar
MeasureName=One

[MeterBar289]
Meter=Bar
MeasureName=One

[MeterBar290]
Meter=Bar
MeasureName=One

[MeterBar291]
Meter=Bar
MeasureName=One

[MeterBar292]
Meter=Bar
MeasureName=One

[MeterBar293]
Meter=Bar
MeasureName=One

[MeterBar294]
Meter=Bar
MeasureName=One

[MeterBar295]
Meter=Bar
MeasureName=One

[MeterBar296]
Meter=Bar
MeasureName=One

[MeterBar297]
Meter=Bar
MeasureName=One

[MeterBar298]
Meter=Bar
MeasureName=One

[MeterBar299]
Meter=Bar
MeasureName=One

[MeterBar300]
Meter=Bar
MeasureName=One

[MeterBar301]
Meter=Bar
MeasureName=One

[MeterBar302]
Meter=Bar
MeasureName=One

[MeterBar303]
Meter=Bar
MeasureName=One

[MeterBar304]
Meter=Bar
MeasureName=One

[MeterBar305]
Meter=Bar
MeasureName=One

[MeterBar306]
Meter=Bar
MeasureName=One

[MeterBar307]
Meter=Bar
MeasureName=One

[MeterBar308]
Meter=Bar
MeasureName=One

[MeterBar309]
Meter=Bar
MeasureName=One

[MeterBar310]
Meter=Bar
MeasureName=One

[MeterBar311]
Meter=Bar
MeasureName=One

[MeterBar312]
Meter=Bar
MeasureName=One

[MeterBar313]
Meter=Bar
MeasureName=One

[MeterBar314]
Meter=Bar
MeasureName=One

[MeterBar315]
Meter=Bar
MeasureName=One

[MeterBar316]
Meter=Bar
MeasureName=One

[MeterBar317]
Meter=Bar
MeasureName=One

[MeterBar318]
Meter=Bar
MeasureName=One

[MeterBar319]
Meter=Bar
MeasureName=One

[MeterBar320]
Meter=Bar
MeasureName=One

[MeterBar321]
Meter=Bar
MeasureName=One

[MeterBar322]
Meter=Bar
MeasureName=One

[MeterBar323]
Meter=Bar
MeasureName=One

[MeterBar324]
Meter=Bar
MeasureName=One

[MeterBar325]
Meter=Bar
MeasureName=One

[MeterBar326]
Meter=Bar
MeasureName=One

[MeterBar327]
Meter=Bar
MeasureName=One

[MeterBar328]
Meter=Bar
MeasureName=One

[MeterBar329]
Meter=Bar
MeasureName=One

[MeterBar330]
Meter=Bar
MeasureName=One

[MeterBar331]
Meter=Bar
MeasureName=One

[MeterBar332]
Meter=Bar
MeasureName=One

[MeterBar333]
Meter=Bar
MeasureName=One

[MeterBar334]
Meter=Bar
MeasureName=One

[MeterBar335]
Meter=Bar
MeasureName=One

[MeterBar336]
Meter=Bar
MeasureName=One

[MeterBar337]
Meter=Bar
MeasureName=One

[MeterBar338]
Meter=Bar
MeasureName=One

[MeterBar339]
Meter=Bar
MeasureName=One

[MeterBar340]
Meter=Bar
MeasureName=One

[MeterBar341]
Meter=Bar
MeasureName=One

[MeterBar342]
Meter=Bar
MeasureName=One

[MeterBar343]
Meter=Bar
MeasureName=One

[MeterBar344]
Meter=Bar
MeasureName=One

[MeterBar345]
Meter=Bar
MeasureName=One

[MeterBar346]
Meter=Bar
MeasureName=One

[MeterBar347]
Meter=Bar
MeasureName=One

[MeterBar348]
Meter=Bar
MeasureName=One

[MeterBar349]
Meter=Bar
MeasureName=One

[MeterBar350]
Meter=Bar
MeasureName=One

[MeterBar351]
Meter=Bar
MeasureName=One

[MeterBar352]
Meter=Bar
MeasureName=One

[MeterBar353]
Meter=Bar
MeasureName=One

[MeterBar354]
Meter=Bar
MeasureName=One

[MeterBar355]
Meter=Bar
MeasureName=One

[MeterBar356]
Meter=Bar
MeasureName=One

[MeterBar357]
Meter=Bar
MeasureName=One

[MeterBar358]
Meter=Bar
MeasureName=One

[MeterBar359]
Meter=Bar
MeasureName=One

[MeterBar360]
Meter=Bar
MeasureName=One

[MeterBar361]
Meter=Bar
MeasureName=One

[MeterBar362]
Meter=Bar
MeasureName=One

[MeterBar363]
Meter=Bar
MeasureName=One

[MeterBar364]
Meter=Bar
MeasureName=One

[MeterBar365]
Meter=Bar
MeasureName=One

[MeterBar366]
Meter=Bar
MeasureName=One

[MeterBar367]
Meter=Bar
MeasureName=One

[MeterBar368]
Meter=Bar
MeasureName=One

[MeterBar369]
Meter=Bar
MeasureName=One

[MeterBar370]
Meter=Bar
MeasureName=One

[MeterBar371]
Meter=Bar
MeasureName=One

[MeterBar372]
Meter=Bar
MeasureName=One

[MeterBar373]
Meter=Bar
MeasureName=One

[MeterBar374]
Meter=Bar
MeasureName=One

[MeterBar375]
Meter=Bar
MeasureName=One

[MeterBar376]
Meter=Bar
MeasureName=One

[MeterBar377]
Meter=Bar
MeasureName=One

[MeterBar378]
Meter=Bar
MeasureName=One

[MeterBar379]
Meter=Bar
MeasureName=One

[MeterBar380]
Meter=Bar
MeasureName=One

[MeterBar381]
Meter=Bar
MeasureName=One

[MeterBar382]
Meter=Bar
MeasureName=One

[MeterBar383]
Meter=Bar
MeasureName=One

[MeterBar384]
Meter=Bar
MeasureName=One

[MeterBar385]
Meter=Bar
MeasureName=One

[MeterBar386]
Meter=Bar
MeasureName=One

[MeterBar387]
Meter=Bar
MeasureName=One

[MeterBar388]
Meter=Bar
MeasureName=One

[MeterBar389]
Meter=Bar
MeasureName=One

[MeterBar390]
Meter=Bar
MeasureName=One

[MeterBar391]
Meter=Bar
MeasureName=One

[MeterBar392]
Meter=Bar
MeasureName=One

[MeterBar393]
Meter=Bar
MeasureName=One

[MeterBar394]
Meter=Bar
MeasureName=One

[MeterBar395]
Meter=Bar
MeasureName=One

[MeterBar396]
Meter=Bar
MeasureName=One

[MeterBar397]
Meter=Bar
MeasureName=One

[MeterBar398]
Meter=Bar
MeasureName=One

[MeterBar399]
Meter=Bar
MeasureName=One

[MeterBar400]
Meter=Bar
MeasureName=One

[MeterBar401]
Meter=Bar
MeasureName=One

[MeterBar402]
Meter=Bar
MeasureName=One

[MeterBar403]
Meter=Bar
MeasureName=One

[MeterBar404]
Meter=Bar
MeasureName=One

[MeterBar405]
Meter=Bar
MeasureName=One

[MeterBar406]
Meter=Bar
MeasureName=One

[MeterBar407]
Meter=Bar
MeasureName=One

[MeterBar408]
Meter=Bar
MeasureName=One

[MeterBar409]
Meter=Bar
MeasureName=One

[MeterBar410]
Meter=Bar
MeasureName=One

[MeterBar411]
Meter=Bar
MeasureName=One

[MeterBar412]
Meter=Bar
MeasureName=One

[MeterBar413]
Meter=Bar
MeasureName=One

[MeterBar414]
Meter=Bar
MeasureName=One

[MeterBar415]
Meter=Bar
MeasureName=One

[MeterBar416]
Meter=Bar
MeasureName=One

[MeterBar417]
Meter=Bar
MeasureName=One

[MeterBar418]
Meter=Bar
MeasureName=One

[MeterBar419]
Meter=Bar
MeasureName=One

[MeterBar420]
Meter=Bar
MeasureName=One

[MeterBar421]
Meter=Bar
MeasureName=One

[MeterBar422]
Meter=Bar
MeasureName=One

[MeterBar423]
Meter=Bar
MeasureName=One

[MeterBar424]
Meter=Bar
MeasureName=One

[MeterBar425]
Meter=Bar
MeasureName=One

[MeterBar426]
Meter=Bar
MeasureName=One

[MeterBar427]
Meter=Bar
MeasureName=One

[MeterBar428]
Meter=Bar
MeasureName=One

[MeterBar429]
Meter=Bar
MeasureName=One

[MeterBar430]
Meter=Bar
MeasureName=One

[MeterBar431]
Meter=Bar
MeasureName=One

[MeterBar432]
Meter=Bar
MeasureName=One

[MeterBar433]
Meter=Bar
MeasureName=One

[MeterBar434]
Meter=Bar
MeasureName=One

[MeterBar435]
Meter=Bar
MeasureName=One

[MeterBar436]
Meter=Bar
MeasureName=One

[MeterBar437]
Meter=Bar
MeasureName=One

[MeterBar438]
Meter=Bar
MeasureName=One

[MeterBar439]
Meter=Bar
MeasureName=One

[MeterBar440]
Meter=Bar
MeasureName=One

[MeterBar441]
Meter=Bar
MeasureName=One

[MeterBar442]
Meter=Bar
MeasureName=One

[MeterBar443]
Meter=Bar
MeasureName=One

[MeterBar444]
Meter=Bar
MeasureName=One

[MeterBar445]
Meter=Bar
MeasureName=One

[MeterBar446]
Meter=Bar
MeasureName=One

[MeterBar447]
Meter=Bar
MeasureName=One

[MeterBar448]
Meter=Bar
MeasureName=One

[MeterBar449]
Meter=Bar
MeasureName=One

[MeterBar450]
Meter=Bar
MeasureName=One

[MeterBar451]
Meter=Bar
MeasureName=One

[MeterBar452]
Meter=Bar
MeasureName=One

[MeterBar453]
Meter=Bar
MeasureName=One

[MeterBar454]
Meter=Bar
MeasureName=One

[MeterBar455]
Meter=Bar
MeasureName=One

[MeterBar456]
Meter=Bar
MeasureName=One

[MeterBar457]
Meter=Bar
MeasureName=One

[MeterBar458]
Meter=Bar
MeasureName=One

[MeterBar459]
Meter=Bar
MeasureName=One

[MeterBar460]
Meter=Bar
MeasureName=One

[MeterBar461]
Meter=Bar
MeasureName=One

[MeterBar462]
Meter=Bar
MeasureName=One

[MeterBar463]
Meter=Bar
MeasureName=One

[MeterBar464]
Meter=Bar
MeasureName=One

[MeterBar465]
Meter=Bar
MeasureName=One

[MeterBar466]
Meter=Bar
MeasureName=One

[MeterBar467]
Meter=Bar
MeasureName=One

[MeterBar468]
Meter=Bar
MeasureName=One

[MeterBar469]
Meter=Bar
MeasureName=One

[MeterBar470]
Meter=Bar
MeasureName=One

[MeterBar471]
Meter=Bar
MeasureName=One

[MeterBar472]
Meter=Bar
MeasureName=One

[MeterBar473]
Meter=Bar
MeasureName=One

[MeterBar474]
Meter=Bar
MeasureName=One

[MeterBar475]
Meter=Bar
MeasureName=One

[MeterBar476]
Meter=Bar
MeasureName=One

[MeterBar477]
Meter=Bar
MeasureName=One

[MeterBar478]
Meter=Bar
MeasureName=One

[MeterBar479]
Meter=Bar
MeasureName=One

[MeterBar480]
Meter=Bar
MeasureName=One

[MeterBar481]
Meter=Bar
MeasureName=One

[MeterBar482]
Meter=Bar
MeasureName=One

[MeterBar483]
Meter=Bar
MeasureName=One

[MeterBar484]
Meter=Bar
MeasureName=One

[MeterBar485]
Meter=Bar
MeasureName=One

[MeterBar486]
Meter=Bar
MeasureName=One

[MeterBar487]
Meter=Bar
MeasureName=One

[MeterBar488]
Meter=Bar
MeasureName=One

[MeterBar489]
Meter=Bar
MeasureName=One

[MeterBar490]
Meter=Bar
MeasureName=One

[MeterBar491]
Meter=Bar
MeasureName=One

[MeterBar492]
Meter=Bar
MeasureName=One

[MeterBar493]
Meter=Bar
MeasureName=One

[MeterBar494]
Meter=Bar
MeasureName=One

[MeterBar495]
Meter=Bar
MeasureName=One

[MeterBar496]
Meter=Bar
MeasureName=One

[MeterBar497]
Meter=Bar
MeasureName=One

[MeterBar498]
Meter=Bar
MeasureName=One

[MeterBar499]
Meter=Bar
MeasureName=One

[MeterBar500]
Meter=Bar
MeasureName=One