[Variables]

; Save this text file and refresh the skin after editing these settings!

Bands=40
; Number of peaks to interpolate from
; Activate the GenerateMeasures.ini file after changing this value

Width=400
Height=125
; "Real" spectrum dimensions
; Activate the GenerateMeters.ini file after changing these values

Scale=2
; Magnification of the real spectrum, increasing viewing size and performance at the expense of quality

Color=161,186,220
; Don't add an alpha value at the end

AverageSize=4
; Number of past measure values to average from, increasing continuity

Port=Output
ID=""
FFTSize=8192
FFTOverlap=(#FFTSize#*0.5)
FFTAttack=0
FFTDecay=300
FreqMin=20
FreqMax=20000
Sensitivity=35
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel

; Context menu environment variables
Config=Frost
ConfigPath=C:\Users\YourName\My Documents\Rainmeter\Skins\Frost\Frost.ini
Flip=0
